import { prisma } from "../db";
import { tagNormalize } from "./normalization";

export const mockExtractor = async (runId: string, projectId: string, fileIds: string[]) => {
    // deterministic mock dataset generated by AI for "files"
    // simulate some rows
    const mockData = [
        { tagRaw: "RTU-1", category: "Rooftop Unit", level: "Roof", location: "Sector A", cfm: 12000, voltage: 480, phase: 3, specSection: "23 74 13", confidence: 0.98 },
        { tagRaw: "ERU-1", category: "Energy Recovery Unit", level: "Roof", location: "Sector B", cfm: 8000, voltage: 480, phase: 3, specSection: "23 74 13", confidence: 0.95 },
        { tagRaw: "AHU-3", category: "Air Handling Unit", level: "L2", location: "Mech Room 201", cfm: 6500, voltage: 480, phase: 3, specSection: "23 73 13", confidence: 0.90 },
        { tagRaw: "Pump 1", category: "Hydronic Pump", level: "L1", location: "Main Plant", gpm: 250, voltage: 480, phase: 3, specSection: "23 21 23", confidence: 0.82 }, // lower confidence
        { tagRaw: "Mix Valve 1", category: "Mixing Valve", level: "L1", location: "Main Plant", gpm: 250, specSection: "23 21 13", confidence: 0.88 },
        { tagRaw: "VAV-1-1", category: "VAV Box", level: "L1", location: "Room 101", cfm: 400, voltage: 277, phase: 1, specSection: "23 36 00", confidence: 0.72 } // low confidence
    ];

    for (const m of mockData) {
        const norm = tagNormalize(m.tagRaw);
        await prisma.extractionRow.create({
            data: {
                runId,
                projectId,
                sourceFileId: fileIds.length > 0 ? fileIds[0] : null,
                tagRaw: m.tagRaw,
                tagNormalized: norm,
                category: m.category,
                level: m.level,
                location: m.location,
                qty: 1,
                airflowCfm: m.cfm,
                gpm: m.gpm,
                voltage: m.voltage,
                phase: m.phase,
                specSection: m.specSection,
                confidence: m.confidence,
                status: "PENDING",
                pageNumber: Math.floor(Math.random() * 10) + 1,
                boundingBox: JSON.stringify({ x: 100, y: 150, w: 500, h: 40 }),
                snippetUrl: "/placeholder-snippet.jpg" // Placeholder for an actual cropped image route
            }
        });
    }

    await prisma.extractionRun.update({
        where: { id: runId },
        data: { status: "COMPLETED", completedAt: new Date(), summary: JSON.stringify({ detected: mockData.length, lowConfidence: mockData.filter(m => m.confidence < 0.85).length }) }
    });
};
